version: 2

sphinx:
   configuration: docs/source/conf.py

formats:
   - pdf

python:
   install:
     - method: pip
       path: .
     - requirements: docs/requirements-docs.txt

build:
   os: ubuntu-20.04
   tools:
      python: "3"